FROM dunglas/frankenphp:php8.3

WORKDIR /app

RUN apt-get update \
    && apt-get install -y git unzip libicu-dev libzip-dev \
    && docker-php-ext-install intl zip \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY composer.json composer.lock ./

RUN composer install \
    --no-dev \
    --no-interaction \
    --prefer-dist \
    --optimize-autoloader

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

RUN chown -R www-data:www-data storage bootstrap/cache

ENV SERVER_NAME=:80

CMD ["frankenphp", "php-server", "-r", "public/"]